### ISSUE TITLE
Why --watch could not work in Intellij IDEA?

### ISSUE THREAD

**Issue by amorphius** [tomlokhorst/CoffeeSharp#14]
I launched this command inside my js directory
coffee -c ./ -o ./ --watch

I have one coffee file in this directory. First compile went well, then I've edited this coffee file in Intellij IDEA, but js file was not regenerated. Why is that? Everything works fine when editing in some another text editor (I've tried notepad++).

**Comment by tomlokhorst** [comment]
I'm cleaning up old open issues. Sorry for not replying sooner.
If this is still an issue, please reopen this.
