### ISSUE TITLE
FSharp.Core 4.0.0 FileNotFound exception

### ISSUE THREAD

**Issue by internetbird** [tomlokhorst/CoffeeSharp#15]
Hi,
 I downloaded the CoffeeSharp-0.5.zip from the CoffeeSharp website but when I try to run Coffee.exe I get a "FSharp.Core 4.0.0 FileNotFound" exception.

I am running on Win8 64bit and have VS2013 with F# installed.

Do you have any idea why I am getting this error? Is there something wrong with the package?

**Comment by tomlokhorst** [comment]
I'm cleaning up old open issues. Sorry for not replying sooner.
If this is still an issue, please reopen this.
